sonar.projectKey=ci-java-sample
sonar.projectName=CI Java Sample
sonar.projectVersion=1.0

# Code source et tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Couverture de code JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# URL SonarQube et authentification
sonar.host.url=http://localhost:9000
sonar.login=sqp_b1604b5aed3f5342c584904cce96f4f0394b7


